# Generated by Django 5.2.7 on 2025-10-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_producto_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='user',
            new_name='usuario',
        ),
    ]
